### ISSUE TITLE
Product variants are not created for new module versions, if product variants related to old module versions are already created.

### ISSUE THREAD

**Issue by st-aprajapati** [OCA/apps-store#11]
Steps to reproduce issue:
1) Go to Github menu → Repositories → Click on Branches sync.
2) Click on “Branches” button.
3) Select any branch. For example v9.
4) Click on “Download Source Code”.
5) Click on “Analyze Source Code”.
6) Go to settings → Automation → Scheduled Actions and run scheduler of “Create product variants for each module version“.
7) It will create product template and variants for v9.
8) Fetch module for v10 or for any version by following above steps.
9) Run scheduler again to create product variant for newer version. 
 
Now, It is not creating product variant for newer version. Have I missed something?

**Comment by bizzappdev** [comment]
@st-aprajapati Please try this with https://github.com/OCA/apps-store/pull/10 it is working properly with dependency.

**Comment by st-aprajapati** [comment]
@bizzappdev  Ok, I will try.
