### ISSUE TITLE
Connexion is not secure in https://odoo-community.org/shop

### ISSUE THREAD

**Issue by elicoidal** [OCA/apps-store#26]
![screenshot from 2018-10-03 17 17 24](https://user-images.githubusercontent.com/7600613/46420393-39fc6500-c730-11e8-8b73-bd4a27bcac42.png)

Some images shows insecure connection.

**Comment by bizzappdev** [comment]
@elicoidal  This will be solved by https://github.com/OCA/apps-store/pull/25/files

**Comment by StephanRozendaal** [comment]
@bizzappdev Are you sure that PR will fix it?
It seems to be a proxy setting on the server odoo-community.org is running on.
Who can look into this?

**Comment by bizzappdev** [comment]
@StephanRozendaal I am sure it will solve. because it is right now using {{request.httprequest.url_root}} and it has http and not https.
for more check the screenshot.
![selection_214](https://user-images.githubusercontent.com/4273984/46602662-69cfb200-cb0e-11e8-8df5-585673c47419.jpg)

**Comment by StephanRozendaal** [comment]
@bizzappdev You are right!

**Comment by elicoidal** [comment]
@gurneyalex Is this something we need to look into our nginx?

**Comment by pedrobaeza** [comment]
I think it can be proxy_mode = True conf value. cc @sbidoul

**Comment by sbidoul** [comment]
proxy_mode was indeed false. This is fixed now.
