### ISSUE TITLE
[RFC] Module sorting should be improved

### ISSUE THREAD

**Issue by elicoidal** [OCA/apps-store#27]
Currently arriving on firs page are displayed modules from v6.1, starting with W. The sorting is not clear.
I suggest sorting by latest version then alphabetical order or commit date.

cc @OCA/board @bizzappdev @StephanRozendaal @RoelAdriaans

**Comment by bizzappdev** [comment]
@elicoidal  Agree. 
we should also have the sorting properly when the search will be done.
priority:
1. Name of the module
2. Author Of the Module.
3. Description of the module.

Please correct if sorting order should be different

**Comment by StephanRozendaal** [comment]
I like the proposition of @elicoidal 
1. Sort on latest version of Odoo
2a. Sort on commit date of the specific module
or
2b. Sort on alphabetical order of module.

In this case my preference goes to commit date, because this is similar to what github does on the repos in OCA.

**Comment by bizzappdev** [comment]
@StephanRozendaal Yes, that is when nothing in search.
but if the search will be provided then the search keyword also has to be respected.

Sorry I was not clear on my first comment.

**Comment by StephanRozendaal** [comment]
@bizzappdev Ah right, I understand now!
I agree with you on which fields to search.

**Comment by elicoidal** [comment]
I am not sure sorting on description will provide relevant output.
We should select between Author/version/Category which seems the simplest and less problematic
