### ISSUE TITLE
Front page image size is uneven

### ISSUE THREAD

**Issue by elicoidal** [OCA/apps-store#28]
![screenshot from 2018-10-03 17-21-01](https://user-images.githubusercontent.com/7600613/46420645-ceff5e00-c730-11e8-9612-9440bf122520.png)

All front page logos should be displayed with the same size.

**Comment by bizzappdev** [comment]
This will be solved by https://github.com/OCA/apps-store/pull/25

**Comment by elicoidal** [comment]
![image](https://user-images.githubusercontent.com/7600613/48316354-cda03b80-e5e2-11e8-9ad1-b471235f4b59.png)

Seems better but not completely correct.
Could we make the image bigger or like a cover (similar to odoo apps?)
cc @oscarolar @bizzappdev

**Comment by elicoidal** [comment]
@bizzappdev It seems that we still have the issue:
![image](https://user-images.githubusercontent.com/7600613/49376283-0c6b7200-f707-11e8-8465-64a23fa6eab1.png)

I would suggest the following but not sure how feasible or simple:
* If image key present in the manifest, we use the image and it should be the full size of the space (like in odoo apps) either in the kanban or in the form detailed page
* otherwise (we assume it is an icon): the size should be fixed to 1/4 or 1/8 of the space (both in kanban and detailed page).

What do you think?
