### ISSUE TITLE
[RFC] Filters button are redundant

### ISSUE THREAD

**Issue by elicoidal** [OCA/apps-store#29]
![screenshot from 2018-10-03 17 30 30](https://user-images.githubusercontent.com/7600613/46421285-1a663c00-c732-11e8-88f7-d83b01ab3e83.png)

I would tend to keep the top button to give more space to the modules list.

cc @OCA/board @bizzappdev @StephanRozendaal @RoelAdriaans

**Comment by pedrobaeza** [comment]
For me it's the contrary. You should remove the left part, and it's possible directly from customize view.

**Comment by bizzappdev** [comment]
@elicoidal @gurneyalex  @pedrobaeza  we can just remove those options from the configuration of the Shop. someone from you guys has to take care for more please find a screenshot. Just disable the e-commerce category and Product attribute filter option 
![selection_212](https://user-images.githubusercontent.com/4273984/46468216-780b8e80-c7ed-11e8-9333-2fa4bd86e698.jpg)

**Comment by elicoidal** [comment]
Done :+1:
