### ISSUE TITLE
"Sort by" - add more sorting options

### ISSUE THREAD

**Issue by elicoidal** [OCA/apps-store#30]
Record the download numbers in the variant
Add the possibility to sort by:
* download number
* Most rated

![screenshot from 2018-10-03 17 35 37](https://user-images.githubusercontent.com/7600613/46421651-daec1f80-c732-11e8-8a27-ea2547301b4c.png)

**Comment by bizzappdev** [comment]
@elicoidal  for that we have to keep a record for the downloaded module.
do we have to go with Logged in user wise or IP wise download or just plain Download has to be there?

**Comment by StephanRozendaal** [comment]
I'd say we count the downloads when the download action is triggered from Odoo.

**Comment by bizzappdev** [comment]
then it will be possible to download modules from the script and like normal odoo apps store. everyone will try to increase the count of their own module. at the end, we will not have proper count data.

**Comment by elicoidal** [comment]
@bizzappdev there is always this possibility indeed.
I think the population of the OCA is not really this kind of player but that is a possibility.
BTW, Shall we add a captcha for the download screen?
Maybe we record a log for every download (IP, user name, module name, version, date/time)

cc @OCA/board

**Comment by bizzappdev** [comment]
@elicoidal  yes we can have record IP, Module name version, DateTime. Not sure about username because right now it is possible to download without login.
we can go with the login user only or the captcha.

**Comment by elicoidal** [comment]
I think Catpcha is good enough. I am a bit worried about recording the username for GDPR reasons. cc @OCA/board

**Comment by bizzappdev** [comment]
okay, that will be perfect.

**Comment by bizzappdev** [comment]
Solved with https://github.com/OCA/apps-store/pull/46
