### ISSUE TITLE
Discrepency in the number of products/variants in backend

### ISSUE THREAD

**Issue by elicoidal** [OCA/apps-store#33]
In products:
![screenshot from 2018-10-04 07 37 48](https://user-images.githubusercontent.com/7600613/46454855-a87d0980-c7a8-11e8-8001-3d62be16d52f.png)

In variants
![screenshot from 2018-10-04 07 39 21](https://user-images.githubusercontent.com/7600613/46454859-adda5400-c7a8-11e8-9bbf-772cf54ea815.png)

Besides the field "Odoo Module" appears 2 times in the list of fields in the product variant filter interface

**Comment by RoelAdriaans** [comment]
The difference in products and variants it too be expected:

- Product template is the module (For example, audit_log)
- Product variant is the version (7.0, 8.0, 9.0, 10.0, 11.0)

**Comment by bizzappdev** [comment]
Indeed. Also in product variant it is the m2o to odoo module version. (Might be change needed to have proper caption). And in product template it is odoo module.

**Comment by pedrobaeza** [comment]
Closing as answered.
