### ISSUE TITLE
Maturity level: PR

### ISSUE THREAD

**Issue by hbrunn** [OCA/apps-store#34]
during some discussions at the code sprint I got the impression most unrest about reviews, conventions and merging stems from the fact that stuff has to be merged to be visible, and that's what people care for much more than the actual merge.

So why don't we approach the maturity slightly differently: We scan open PRs for the ones that add a module, that should be simple to detect. If the PR is done by an OCA member (in order to avoid people being able to spam the webshop), we add it to the shop with maturity alpha. So we get early releases, but don't have to merge subpar code. The advantage I see is that this way, a module can mature without creating possible problems in a branch by being merged prematurely (unprotected imports, wrong monkey patching and the like). This can also be a selling point for the OCA membership, and can inform us about which modules users like most, thus allowing us to direct the review efforts to the ones that are most wide-spread. Plus there's no interaction needed by anyone to get something published, which probably would stay a bottleneck.

cc @OCA/board

**Comment by elicoidal** [comment]
I like the idea. We need to see technically how to do it but it would allow to give a sense of what would land in the repository.
:+1:

**Comment by sbidoul** [comment]
Sounds like a good idea to me.

**Comment by hbrunn** [comment]
In pseudo python I'd think of something like this:

```python
for pr in open_prs:
    if not pr.author.is_oca_member(): # how about also pr.is_green()?
        continue
    is_only_new_modules = True
    for path in pr.changed_files:
        path = path.first_path_component
        if path in whilelisted:
            # whitelisted would be .travis.yml and other stuff you do for tests
            continue
        if path.exists_in_main_branch:
            is_only_new_modules = False
            break
    if not is_only_new_modules:
        continue
    cherry_pick_pr_onto_checkout_of_main_branch_we_scan_for_the_shop()
    # we might better filter out only the new modules so that changes in
    # .travis.yml can't conflict
```

Doing this only for green branches would give people a good incentive to help greenifying branches...

**Comment by elicoidal** [comment]
Will have to deal with the green/red <-> active/inactive product (might be a bit confusing for users because products might disappear overnight).
Been Alpha I think user will understand that there might be glitches.

**Comment by hbrunn** [comment]
well, there are a _lot_ of PRs which will crash people's servers. But so do incompatible addons (RFC: Implement the `breaks` option in https://github.com/OCA/server-tools/tree/10.0/base_manifest_extension and use that to be able to avoid users shooting their own foot), and there will be a best practice tip that you always ever should test new modules in a test environment, right?

**Comment by elicoidal** [comment]
That is the point of tagging them Alpha IMO and this is good enough to tell the people not to use in Production.
We might add some additional text in the filename "-mature" or "-alpha" and for not stable/mature modules, I am in favor to add a warning when people clicks on "Download": "Please be aware that current version of the module is not suitable for production environment" (or similar).
What do you think?
