### ISSUE TITLE
[RFC] `breaks` in manifest

### ISSUE THREAD

**Issue by hbrunn** [OCA/apps-store#35]
To make the shop a pleasant experience, we should be able to tell users that some module doesn't work in their specific situation. Might be view incompatibilities, incompatible overrides or the like.

I've put a `breaks` key in the roadmap of https://github.com/OCA/server-tools/tree/10.0/base_manifest_extension, I think it would be useful to implement that for the shop. Then we can add this information to our ecosystem, making stuff more stable for everyone. We can also go crazy and add more debianish keys, like `recommends` or `suggests`. Versioned dependencies also could be helpful in the shop context.

**Comment by elicoidal** [comment]
Let us know when the key is available.
cc @bizzappdev @oscarolar

**Comment by RoelAdriaans** [comment]
Key should first be made in the https://github.com/OCA/interface-github/ repo in github_connector_oca module.. 

It the breaks already an official maintainers key? There is also an conflits key, don't they do the same thing?

**Comment by hbrunn** [comment]
do you mean there is already a `conflicts` key in Odoo? If so, we absolutely use this and backport as a module to earlier versions. Or are you proposing to call it `conflicts` instead of `breaks`? In that case, I just read the [debian policy manual](https://www.debian.org/doc/debian-policy/ch-relationships.html#packages-which-break-other-packages-breaks) about that, and the difference there is very specific to the way apt works. One is as good for me as the other, if anyone has strong feelings about any of them

**Comment by elicoidal** [comment]
one way or another is fine by me (better the Odoo one if any)

**Comment by sbidoul** [comment]
@hbrunn such a key exists and is supported in Odoo 11. It's named [excludes](https://github.com/odoo/odoo/blob/a587325ca7a2da58cea5f1b8075426e92d114e61/odoo/addons/base/module/module.py#L711). In some modules we have used `conflicts` in the past but it was only informative.
