### ISSUE TITLE
Bad rendering of links inside README

### ISSUE THREAD

**Issue by sbidoul** [OCA/apps-store#37]
Example: 

https://odoo-community.org/shop/product/mis-builder-budget-1639
![image](https://user-images.githubusercontent.com/692075/47910525-75a35f80-de93-11e8-8077-a2020dbbd904.png)

These render correctly in the backend or on pypi or on apps.odoo.com.

**Comment by elicoidal** [comment]
Could this be only the table of content. I know that some renderers do not take them into account.

**Comment by bizzappdev** [comment]
this will be closed with #42

**Comment by sbidoul** [comment]
@bizzappdev the repo link is correct now, but the readme is always empty.

**Comment by bizzappdev** [comment]
@sbidoul  are you sure on the backend the module version has the description from README ?

**Comment by elicoidal** [comment]
You can check any module in the apps store: it is empty @bizzappdev

**Comment by bizzappdev** [comment]
@elicoidal  yes some has while some do not display. 
seems like CSS change from this issue is causing the problem
I have an alternative solution I am doing a PR but IMO the CSS experts have to review it as I am just a newbie for CSS.

**Comment by sbidoul** [comment]
This seems to be resolved. Thanks!
