### ISSUE TITLE
Cannot select v12 in the filter

### ISSUE THREAD

**Issue by elicoidal** [OCA/apps-store#38]
Not clear the reason why: are modules in v12 or is it the filter itself

![screenshot from 2018-11-02 19-40-11](https://user-images.githubusercontent.com/7600613/47934546-cc328d00-ded7-11e8-9efd-a25388584c28.png)

**Comment by sbidoul** [comment]
Apparently the Odoo Version attribute had no value 12.0. I created it manually.

I guess the apps-store module does not create it automatically.

**Comment by sbidoul** [comment]
Now I'm not sure what to do to create the products. I tried launching the product creation cron but it did nothing apparently. @bizzappdev ?

**Comment by bizzappdev** [comment]
@sbidoul  Let me check the logic for the same as we were not the original developer for the creating product. 
I will check and let you know

**Comment by sbidoul** [comment]
I had a quick look at that code. The problem seems rather profound, as the product creation cron starts by looking at modules that have no linked product template. So at first glance it discovers new modules but it will never discover new versions of existing modules.

**Comment by bizzappdev** [comment]
yes seems like you are right, We have to add an update product cron job which will support the new version added.

**Comment by elicoidal** [comment]
This is currently solved so closing
