### ISSUE TITLE
Cannot find module account_invoice_kanban

### ISSUE THREAD

**Issue by elicoidal** [OCA/apps-store#39]
available in v8 and v10 in https://github.com/OCA/account-invoicing

![screenshot from 2018-11-02 19-46-27](https://user-images.githubusercontent.com/7600613/47934619-0bf97480-ded8-11e8-8fa5-2f8059348911.png)

**Comment by pedrobaeza** [comment]
This is because the search doesn't look on technical name.

**Comment by bizzappdev** [comment]
Not sure how to reproduce.
from the below link "Just by entering the name of the product it is listed
https://odoo-community.org/shop?search=account_invoice_kanban
![selection_227](https://user-images.githubusercontent.com/4273984/47949559-950dbb80-df6b-11e8-976f-2bc30d00ae6b.jpg)

**Comment by elicoidal** [comment]
you are right: I had an additional filter on version.
Closing for stupid :smile:
