### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/apps-store#4]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x]  apps_download - By @bizzappdev - #12 
- [x]  apps_product_creator - By @tarteo - #9

**Comment by lasley** [comment]
IMO we should switch the default branch of this one back to 10.0 in order to match our mainline development.

**Comment by pedrobaeza** [comment]
Right, done!

**Comment by elicoidal** [comment]
@bizzappdev we would like to migrate our ERP to v11 and use your development.
Do you think it is possible for you to migrate the current developments in August?
If possible could you please contact me via PM?
cc @gdgellatly

**Comment by bizzappdev** [comment]
@elicoidal  yes sure we can plan for the migration of this repo in August.

**Comment by elicoidal** [comment]
@bizzappdev that would be wonderful news!

**Comment by bizzappdev** [comment]
@elicoidal  we are stating migration of code from Monday. let me know if you have any special instruction or something.

**Comment by elicoidal** [comment]
@bizzappdev Thanks a lot for the reactivity!
@gdgellatly will help on the specifics

**Comment by gdgellatly** [comment]
@bizzappdev I'm not sure I have any specifics atm, but ping me if you need me.  The work which hooks into this is currently under review and isn't really tightly coupled.  Really just hyperlinks to modules.  They have just been using website_sale and the github connectors for testing.

How is it going anyway?

**Comment by bizzappdev** [comment]
@gdgellatly I do not get completely what you are trying to point out for the hyperlinks to modules. and website_sale and GitHub.
the migration of the modules is in progress. and I hope it will be ready by next week for review and test.

**Comment by gdgellatly** [comment]
@bizzappdev in the OCA/oca-custom repo there are some v11 PR's that depend (kind of) on the apps-store web front end being migrated to v11.  

Basically you will be able to click on a member or company and it will list their modules.

But they only link to pages, nothing really tightly integrated, and because apps-store really just extends website_sale to date the work has all been done using just that module.

**Comment by elicoidal** [comment]
@bizzappdev How is the migration going? Anything we can help with?

**Comment by elicoidal** [comment]
@bizzappdev Any feedback?

**Comment by bizzappdev** [comment]
@elicoidal  last final testing is needed from our side then we can submit the PR. it will be done by today only.

**Comment by elicoidal** [comment]
Whouaou! that would be wonderful news
cc @gdgellatly
