### ISSUE TITLE
Features to be developed during OCA Days sprint India

### ISSUE THREAD

**Issue by bizzappdev** [OCA/apps-store#44]
We can list the features to be developed during the OCA code sprint (India) on 24th Nov.

**Comment by bizzappdev** [comment]
@elicoidal  can you please list the features for tomorrow?

**Comment by elicoidal** [comment]
@bizzappdev thanks for the opportunity to improve the apps store!
Here are the issues that would need to be fixed:
~https://github.com/OCA/apps-store/issues/41~
https://github.com/OCA/apps-store/issues/37 (some solutions found but not yet fully satisfactory: README is not even rendered anymore).
https://github.com/OCA/apps-store/issues/30
https://github.com/OCA/apps-store/issues/28 (currently the logo is now even but the effect is not very good: I am wondering whether we should have a full width image over the kanban card)
https://github.com/OCA/apps-store/issues/27

This one might be complex and not yet fully validated:
https://github.com/OCA/apps-store/issues/34

Nice to have:
*  create a list view with quick download button
* Migration to v12 is as well an option (along with interface-github)

**Comment by elicoidal** [comment]
cc @OCA/board

**Comment by bizzappdev** [comment]
@elicoidal  #41 and #37  both are already done. the PR is also linked.

for #27 and #34 are still in discussion.

**Comment by elicoidal** [comment]
@bizzappdev #41, I keep it open until we have final confirmation,
#37 currently not satisfactory at least for what I have checked so far
#27 I think the proposed solution in https://github.com/OCA/apps-store/issues/27#issuecomment-427858005 is the minimum for the moment and is good enough
#34 agree: not priority

**Comment by elicoidal** [comment]
@bizzappdev do not hesitate to ping me during the dat if you need some review.

thanks again for the code sprint organization and help on the matter :smile:

**Comment by bizzappdev** [comment]
Yes sure. Thank you for availability. Code sprint will start in 2 hours.

**Comment by bizzappdev** [comment]
#37 and #30 has been taken care.
#30 still need some code to be pushed before it is ready for testing.
