### ISSUE TITLE
Incorrect icons

### ISSUE THREAD

**Issue by sbidoul** [OCA/apps-store#48]
Example here: https://odoo-community.org/shop/product/mis-builder-1636?search=mis+builder

The acsone icon should not be there. It is not obvious where it comes from, as it is used nowhere in that module in github.

**Comment by elicoidal** [comment]
It is probably due to the fact that the algorithm will try to explore any kind of image in the module to display in front and pick the one of the contributor/maintainer in case of absence (a guess as I didnot revisit the code).

We should probably discuss the basic selection rules for images (in order of priority):
1. image tag in manifest
2. icon in description folder
3. standard OCA icon

cc @OCA/board

**Comment by pedrobaeza** [comment]
The module icon should have priority for sure.

**Comment by elicoidal** [comment]
I am not sure here. 
I would like to achieve this:

![image](https://user-images.githubusercontent.com/7600613/49091141-7c897c00-f25f-11e8-81ca-3549d4ad628d.png)

and icons are not suitable by default for this: an image with proper design is better

**Comment by pedrobaeza** [comment]
Well, that's not what is achieved right now any way.

**Comment by elicoidal** [comment]
I know: we are still finetuning :wink:

**Comment by bizzappdev** [comment]
it is taking the priority from https://github.com/OCA/interface-github/blob/11.0/github_connector_odoo/models/odoo_module_version.py#L23
as static/src/img path is first it is taking the icon from that path.
https://github.com/OCA/mis-builder/blob/8.0/mis_builder/static/src/img/icon.png

**Comment by pedrobaeza** [comment]
Agh, curious thing! It's taking an old icon (valid for <v8) that hasn't been removed through all versions. @sbidoul can you please remove it in all branches? Or should I?

**Comment by elicoidal** [comment]
@sbidoul @pedrobaeza Is this taken care of? Is there anything we could help?

**Comment by elicoidal** [comment]
@bizzappdev What do you think about the image management?
Today we have another open issue #28 where the image is not even and I think we can improve without much work.
Shall I start a specific issue for that?

**Comment by pedrobaeza** [comment]
In this case, @sbidoul should remove that old icon in the repo.

**Comment by sbidoul** [comment]
Sorry guys, I lost the thread. What should I do exactly?

**Comment by pedrobaeza** [comment]
Remove the acsone icon in mis-builder in the offending route (static/src/img/icon.png).

**Comment by sbidoul** [comment]
At least the link above shows a [404](https://github.com/OCA/mis-builder/blob/8.0/mis_builder/static/src/img/icon.png) since many weeks. Is there another one?

**Comment by bizzappdev** [comment]
yes as it has been already taken care https://github.com/OCA/mis-builder/commit/9b8f7010522515a174433e56890eff261525eafe
and also proper Image is on app store. 
https://odoo-community.org/shop/product/mis-builder-1636?search=mis+builder

**Comment by pedrobaeza** [comment]
Ok, then this should be correct and can be closed.
