### ISSUE TITLE
[RFC] Priority for search result

### ISSUE THREAD

**Issue by bizzappdev** [OCA/apps-store#53]
Currently when we search it is searching directly on the name, desc, rst/html desc, author and everything.
The result is we have a lot of modules in search and the real meaningful module will be pointed out.

IMO we should have smart sorting (or maybe a proper name) option for sort, which will search include the apps in below orders
1. match with the technical name "=" operator
2. match with the name "=" operator.
3. match with technical name and name with ilike operator.
4. author "=" and "ilike"  operator
5. rest current conditions.

**Comment by bizzappdev** [comment]
@elicoidal @OCA/board  your suggestions are needed

**Comment by elicoidal** [comment]
Personally I would stick to 
* Name
* Technical name
* summary
* author for the search 

Ideally we should have a page "advanced search" where we could tick the fields to search in.
I think it is too soon for that (and too complex). 
Maybe have a simple tick box "Search in README.rst and index.html too" below the search field.

**Comment by bizzappdev** [comment]
yes adding simple boolean will also solve the problem. 
and what about the search with separate words or entire like "Audit Log" or "Audit" and "Log"

I also would like to propose that we should have a direct URL structure based on version and technical name. will that be an added value?

**Comment by elicoidal** [comment]
> and what about the search with separate words or entire like "Audit Log" or "Audit" and "Log"

Personally prefer "Audit Log" but I am sure there are many opinion for one or the other.

We could add a checkbox "Search all terms" (and later why not a "Fuzzy search" one)
@bizzappdev

**Comment by elicoidal** [comment]
@bizzappdev What about this (simple case): is it achieved with current version?

**Comment by bizzappdev** [comment]
@elicoidal  Sorry, I completely missed that. yes, it is achievable. 
basically, default it will search on entire work and if Boolean is there then it will search for all words. easy and achievable.

**Comment by elicoidal** [comment]
Agree

**Comment by bizzappdev** [comment]
okay, Perfect, we will work on the same this week.

**Comment by bizzappdev** [comment]
#58 created for the same. sorry for delay
