### ISSUE TITLE
Search is not working properly

### ISSUE THREAD

**Issue by dreispt** [OCA/apps-store#69]
Although the [current code](https://github.com/OCA/apps-store/blob/12.0/website_apps_store/controllers/main.py#L26) is performing a search on all the relevant fields, including technical name, name and descriptions, my experience in the App store is that it is not working as expected.

Specific example: 

- there is a [`auth_topt`](https://github.com/OCA/server-auth/tree/12.0/auth_totp) module, "MFA Support". The "topt" text is both in the technical name and in the module description.
- searching the App store for ["topt"](https://odoo-community.org/shop?&search=topt) returns no results! 

Any ideas on why this might be?

**Comment by pedrobaeza** [comment]
hehe, you are searching `topt` instead of `totp`.

**Comment by moylop260** [comment]
So fixed

**Comment by dreispt** [comment]
No, I'm still broken 😝 
Thanks for spotting the obvious Pedro.
