### ISSUE TITLE
[RFC] Apps Store front end

### ISSUE THREAD

**Issue by elicoidal** [OCA/apps-store#7]
# Introduction
The modules on this repository aim to build an apps store based on:
* Standard Odoo v10 ecommerce
* Github Connector

Currently 2 modules are available `apps_product_creator` and `apps_download` linked to github-connector modules which information is used to create one product per module:

* `apps_product_creator` will check the new modules in the repositories and create or update the products (one per module and version) in the database. Additionally important information from the manifest are populated in specific fields
*  `apps_download` is responsible to create and update one zip file per module based on the content of Github repository and link  it to the product in Odoo.

A third module is needed to complete the other 2 and display the module specific information in a standard Odoo e-commerce website (front-end).

This document aims to specify the views, data and process to be done via this third module.

# Module information
* Module name: website_apps_store
* Version: v10.0 (compatible Community and Enterprise Edition)
* Dependency: ecommerce, apps_download, apps_product_creator
* License: AGPL-3

# Front-end view
## E-commerce catalogue page
Here is the mock up suggested for the product catalogue page:
![front](https://user-images.githubusercontent.com/7600613/37553486-408e43a8-2a04-11e8-89cf-3ca99ca6b5af.png)

 
Changes expected to the standard e-commerce page:

* Add Author
* Hide the price
* Add Versions supported by the module

Search function should allow:

* Fuzzy search
* Content in module name, author and summary

3 filters widget to be added:

* Author
* Version
* Category

## Product Detailed page
Here is the mock up suggested for the product detailed page:
![detail](https://user-images.githubusercontent.com/7600613/37573565-47c55c46-2b54-11e8-8e33-d77eb0cff7d9.png)

NB: Current design is based on one page for all versions of the module, displaying the module description of the highest version.

Standard Odoo Fields:

* Image
* Product name

Add following fields (based on the manifest of the higher version)

* Module summary
* Radio button with the versions available for the module (From higher to lower, default = higher)
* Button "Download"
* Miscellaneous fields:
  * Technical Name
  * Author
  * Maintainer (Link to Contributor Page - static page in odoo-community.org)
  * License (Link  to the license on the OSI website)
  * Website (URL)
  * Repository (URL)
* HTML description of the product

NB: 
* all link should open in new tab
* Module details (summary, name, description...) should be dynamic depending on the selected version.
* Update Process: Pages are rebuilt every night via cron job after the module information have been update from Github. Only pages from updated modules are to be rebuilt.

## checkout process

1. The visitor will select a module from the catalogue page
2. The visitor select the version he wants to download for the module
3. Visitor clicks on Download button and the download of the zip file linked to the selected product starts in the browser

NB:

*  no login is required for download
* All other checkout buttons should be hidden

# Roadmap:

* add an extensive search based on the content of RST
* Add multiple images if the modules contains multiple screenshots/images/icon.
* Add a donation button

**Comment by elicoidal** [comment]
@OCA/board Please have a look so that we can finish the requirement description

**Comment by bizzappdev** [comment]
@elicoidal  once we have approval we can start working on it, just we will need support for the phantomJS test cases rest we can take care.

**Comment by pedrobaeza** [comment]
Module details (summary, name, description...) should be dynamic depending on the selected version.

**Comment by elicoidal** [comment]
> Module details (summary, name, description...) should be dynamic depending on the selected version.

If possible, much better!

**Comment by bizzappdev** [comment]
Based on variant selection ofcause it will be possible to get values for a specific version.

**Comment by max3903** [comment]
* License: Should be a link to the license on the OSI website
* Author: Should be a link to the Partner page
* Add the "Maintainer" from the manifest file with a link to the Contributor page

**Comment by elicoidal** [comment]
> License: Should be a link to the license on the OSI website

No Problem

> Author: Should be a link to the Partner page

@max3903 we cannot do that because there are multiple possible partner in the key.

> Add the "Maintainer" from the manifest file with a link to the Contributor page

Not sure how the maintainer key is defined (url to github account?). I keep it generic now. We could improve later.

**Comment by jgrandguillaume** [comment]
LGTM :+1:

**Comment by elicoidal** [comment]
@bizzappdev I think we can move forward: do you have contributors ready to help?

**Comment by bizzappdev** [comment]
@elicoidal  we can start the development from the Monday.

**Comment by elicoidal** [comment]
Fantastic!

**Comment by elicoidal** [comment]
@bizzappdev Could you let me know about progress?

**Comment by elicoidal** [comment]
@bizzappdev Could you let me know about progress?

**Comment by bizzappdev** [comment]
@elicoidal  sorry I am still on leave will be back in the office on Friday, we have already some progress on the website design. and also we have to add the support for creating dependency product while creating a product from the module. that is still to do.

**Comment by elicoidal** [comment]
@bizzappdev Great: let me know when I can start reviewing or testing!

**Comment by elicoidal** [comment]
Hi @bizzappdev 
any news? We need to move forward quickly now. Let us know how we can help

**Comment by elicoidal** [comment]
#12 fix it for v11
