### ISSUE TITLE
Error on account_banking_payment_export v8

### ISSUE THREAD

**Issue by yajo** [OCA/apps-store#70]
This is how `account_banking_payment_export` looks for version 8.0:

![Captura de pantalla de 2019-11-12 10-11-42](https://user-images.githubusercontent.com/973709/68662510-d9e01100-0534-11ea-8ac8-f900a8f5b2bc.png)

For lower versions, it looks good.

Link: https://odoo-community.org/shop/product/account-banking-payments-export-infrastructure-121

**Comment by bizzappdev** [comment]
Module is there for v8 version
https://github.com/OCA/bank-payment/tree/8.0/account_banking_payment_export

seems like some missing data from git module.
Can anyone check from the backend about what is missing or any error while getting module information or something?
