### ISSUE TITLE
Categories sync / Odoo

### ISSUE THREAD

**Issue by rousseldenis** [OCA/apps-store#79]
It seems that Odoo modules categories are inconsistent through versions.

- 14.0:
https://github.com/odoo/odoo/blob/14.0/addons/stock/__manifest__.py#L11

- 12.0:
https://github.com/odoo/odoo/blob/12.0/addons/stock/__manifest__.py#L11

I'm wondering what should we do with OCA apps site helping people filtering modules per categories.

Either staying with original ones ?

Or breaking with Odoo ones and maybe creating OCA ones in order to fulfill our specific needs?

@OCA/core-maintainers

**Comment by pedrobaeza** [comment]
Maybe we can create some kind of mapping for homogenizing them.

**Comment by rousseldenis** [comment]
> Maybe we can create some kind of mapping for homogenizing them.

Yeah, that's sound good. We create an RFC for this? In order to fill in documentation accordingly etc,...

**Comment by pedrobaeza** [comment]
I would say to have a new model

`odoo.module.category.public` or similar, with a translatable name, and a table that maps odoo.version and odoo.module.category, and we convert the Odoo category into the public one dynamically on apps store.

We also provide as standard data the mapping for Odoo core categories.
