### ISSUE TITLE
apps_product_creator: External ID not found  attribute_odoo_version 

### ISSUE THREAD

**Issue by bizzappdev** [OCA/apps-store#8]
Hello !
We have used 
Odoo Version attribute in Py file for creating Product's variants
https://github.com/OCA/apps-store/blob/10.0/apps_product_creator/models/odoo_module.py#L90
But it has been added from the demo data. 
https://github.com/OCA/apps-store/blob/10.0/apps_product_creator/__manifest__.py#L22
https://github.com/OCA/apps-store/blob/10.0/apps_product_creator/demo/product_attribute.xml#L6
IMO the place of product_attribute.xml will be in Data tag and folder and not in demo data.
I can change it while working on the website. but just wanted to confirm that Am I right or not.

**Comment by bizzappdev** [comment]
@espo-tony @RoelAdriaans-B-informed  our opinion is needed

**Comment by espo-tony** [comment]
This point was already discussed here:
https://github.com/OCA/apps-store/pull/2#discussion_r150639208

Personally I think there are good reason to place this either in data or in demo.

**Comment by bizzappdev** [comment]
In my opinion, if we are using it is our code then it should be in data. once it will be isntalled on OCA website. they are not going to install demo data ;).
and if we have to have this in demo data then we should have to create a configuration for the Attribute to be used for the creating variant based on odoo version. 
not sure . right now without demo data module is not workable.

**Comment by bizzappdev** [comment]
@legalsylvain can you also review.

**Comment by elicoidal** [comment]
IMO, the version attribute should be data, not demo.
We are building a tool for Odoo modules and this is specific to Odoo and wont change. I see no harm of having it as data.
We can still have a couple of values for Demo data too.

**Comment by elicoidal** [comment]
@bizzappdev Do you have enough information to move forward?
Can we close this issue?

**Comment by bizzappdev** [comment]
@elicoidal  YEs, I was about to ask what is the procedure to get confirmation :) Wee have already started things internally with the changes. but have not committed because I was not sure, I was under the impression we need 2 approval or something. but if you say so I can commit the changes. and continue to work as per new changes,

**Comment by elicoidal** [comment]
No feedback so let's move on.

**Comment by bizzappdev** [comment]
okay
