### ISSUE TITLE
[13.0] apps_download: Error while trying to download an app (base_import_async)

### ISSUE THREAD

**Issue by RachidAlassir** [OCA/apps-store#80]
Error while trying to download an app (base_import_async)

![image](https://user-images.githubusercontent.com/48803268/120932538-29c19280-c6ee-11eb-89c9-bcfe0c22380f.png)

**Comment by sbidoul** [comment]
The download does not seem to work after deploying #81. I see no error in the logs though.

**Comment by joao-p-marques** [comment]
@sbidoul should be fixed with #82 

This was another error missed in the migration.
