### ISSUE TITLE
[13.0] Apps Store

### ISSUE THREAD

**Issue by magicquin** [OCA/apps-store#84]
Hi All,

First off, really appreciate all the hard work you all do!!

Not sure to call this an issue, perhaps more of my probably just not sure I am using the addons correctly. With my use case, Its not to provide download for odoo modules, but to mobile applications I have I have built. 

I create the product, I then add the android files, I then add my own variants, I then update the variant information. How this is where I then come into the issue.

No matter what I have tried, I keep getting 

This product has no valid combination.

Just not sure what I am doing wrong to be honest. Would really appreciate the help.

Thanks in advance.

**Comment by pedrobaeza** [comment]
Sorry, but any custom development is not supported here as issue. Ask in general forums. You can see that this is working in https://odoo-community.org/shop
